name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Clear lockfile
      run : rm package-lock.json
      
    - name: npm install, build, and test
      run: |
        npm ci
        npm test
        npm run build
        
    - name: Deploy to Firebase
      uses: lowply/deploy-firebase@v0.0.2
      
      env:
        CI: true
